/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mirofff.app;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.protobuf.services.ProtoReflectionService;
import java.io.IOException;

public class App {

  public static void main(String[] args) throws IOException, InterruptedException {
    int port = 50001;

    Server server =
        ServerBuilder.forPort(port)
            .addService(new ProductInfoImpl())
            .addService(ProtoReflectionService.newInstance())
            .build()
            .start();

    System.out.println("Server started, listening on " + port);

    Runtime.getRuntime()
        .addShutdownHook(
            new Thread(
                () -> {
                  System.err.println("Shutting down gRPC server since JVM is " + "shutting down");
                  if (server != null) {
                    server.shutdown();
                  }
                  System.err.println("Server shut down");
                }));
    server.awaitTermination();
  }
}
