/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mirofff.app;

class MessageUtils {
  public static String getMessage() {
    return "Hello      World!";
  }
}
